name = "StringNets"
uuid = "9e2abbc2-76ba-48ee-b359-90b5e4e5a52d"
authors = ["xiaoyu-dong"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
